[build]
builder = "nixpacks"

[deploy]
startCommand = "bundle exec rails server -p $PORT -e $RAILS_ENV"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
RAILS_LOG_TO_STDOUT = "true" 