default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mini_blog_development
  username: mini_blog_user
  password: password123
  host: localhost

test:
  <<: *default
  database: mini_blog_test
  username: mini_blog_user
  password: password123
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>